### ISSUE TITLE
Wrong IP connection to the CQ18T

### ISSUE THREAD

**Issue by jfl56** [bitfocus/companion-module-allenheath-cq#1]
After installing the module in Companion, the module can't connect to the CQ18T Mixer. My Mixer is at the 198.168.1.27 IP Adress but it seems the module can't collect correctly my mixer IP adress.
  have the folllowing errors in the log files :

error: TCP connection error: Error: connect ECONNREFUSED ::1:51325
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 51325
}

**Comment by ultimategmbh** [comment]
Thanks for reporting. The problem already came up in the internal beta channel on slack. The issue is already fixed, just needs to be pushed to GitHub again.

**Comment by leonreucher** [comment]
Thanks for reporting. The problem already came up in the internal beta channel on slack. The issue is already fixed, just needs to be pushed to GitHub again.
